set(_AMENT_PACKAGE_NAME "loop_fusion")
set(loop_fusion_VERSION "0.0.0")
set(loop_fusion_MAINTAINER "tony-ws <tony-ws@todo.todo>")
set(loop_fusion_BUILD_DEPENDS "camera_models" "std_msgs" "nav_msgs" "rclcpp" "cv_bridge" "ament_index_cpp" "pcl_conversions" "vins_msgs")
set(loop_fusion_BUILDTOOL_DEPENDS "ament_cmake")
set(loop_fusion_BUILD_EXPORT_DEPENDS "camera_models" "std_msgs" "nav_msgs" "rclcpp" "cv_bridge" "ament_index_cpp" "pcl_conversions" "vins_msgs")
set(loop_fusion_BUILDTOOL_EXPORT_DEPENDS )
set(loop_fusion_EXEC_DEPENDS "camera_models" "std_msgs" "nav_msgs" "rclcpp" "cv_bridge" "ament_index_cpp" "pcl_conversions" "vins_msgs")
set(loop_fusion_TEST_DEPENDS )
set(loop_fusion_GROUP_DEPENDS )
set(loop_fusion_MEMBER_OF_GROUPS )
set(loop_fusion_DEPRECATED "")
set(loop_fusion_EXPORT_TAGS)
list(APPEND loop_fusion_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
