set(_AMENT_PACKAGE_NAME "global_fusion")
set(global_fusion_VERSION "0.0.0")
set(global_fusion_MAINTAINER "tony-ws1 <tony-ws1@todo.todo>")
set(global_fusion_BUILD_DEPENDS "rclcpp" "std_msgs" "nav_msgs" "sensor_msgs" "visualization_msgs")
set(global_fusion_BUILDTOOL_DEPENDS "ament_cmake")
set(global_fusion_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs" "nav_msgs" "sensor_msgs" "visualization_msgs")
set(global_fusion_BUILDTOOL_EXPORT_DEPENDS )
set(global_fusion_EXEC_DEPENDS "rclcpp" "std_msgs" "nav_msgs" "sensor_msgs" "visualization_msgs")
set(global_fusion_TEST_DEPENDS )
set(global_fusion_GROUP_DEPENDS )
set(global_fusion_MEMBER_OF_GROUPS )
set(global_fusion_DEPRECATED "")
set(global_fusion_EXPORT_TAGS)
list(APPEND global_fusion_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
