set(_AMENT_PACKAGE_NAME "camera_models")
set(camera_models_VERSION "0.0.0")
set(camera_models_MAINTAINER "dvorak <dvorak@todo.todo>")
set(camera_models_BUILD_DEPENDS "rclcpp" "std_msgs")
set(camera_models_BUILDTOOL_DEPENDS )
set(camera_models_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs")
set(camera_models_BUILDTOOL_EXPORT_DEPENDS )
set(camera_models_EXEC_DEPENDS "rclcpp" "std_msgs")
set(camera_models_TEST_DEPENDS )
set(camera_models_GROUP_DEPENDS )
set(camera_models_MEMBER_OF_GROUPS )
set(camera_models_DEPRECATED "")
set(camera_models_EXPORT_TAGS)
