set(_AMENT_PACKAGE_NAME "vins")
set(vins_VERSION "0.0.0")
set(vins_MAINTAINER "qintong <qintonguav@gmail.com>")
set(vins_BUILD_DEPENDS "rclcpp" "rcpputils" "std_msgs" "geometry_msgs" "visualization_msgs" "nav_msgs" "tf2" "tf2_ros" "cv_bridge" "camera_models" "image_transport" "pcl_conversions" "vins_msgs")
set(vins_BUILDTOOL_DEPENDS "ament_cmake")
set(vins_BUILD_EXPORT_DEPENDS "rclcpp" "rcpputils" "std_msgs" "geometry_msgs" "visualization_msgs" "nav_msgs" "tf2" "tf2_ros" "cv_bridge" "camera_models" "image_transport" "pcl_conversions" "vins_msgs")
set(vins_BUILDTOOL_EXPORT_DEPENDS )
set(vins_EXEC_DEPENDS "rclcpp" "rcpputils" "std_msgs" "geometry_msgs" "visualization_msgs" "nav_msgs" "tf2" "tf2_ros" "cv_bridge" "camera_models" "image_transport" "pcl_conversions" "vins_msgs")
set(vins_TEST_DEPENDS )
set(vins_GROUP_DEPENDS )
set(vins_MEMBER_OF_GROUPS )
set(vins_DEPRECATED "")
set(vins_EXPORT_TAGS)
list(APPEND vins_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
